"""Create a synchronized multi-view test video from captured streams.

Combines multiple video files into a single grid layout for visual synchronization testing.
If LSL JSONL recordings exist (from `--record-lsl` in ffmpeg_multicap), the videos are
time-aligned based on the first LSL timestamp per stream.

Optionally includes DPA microphone audio synchronized with the video grid. The audio is
aligned with the same synchronization offsets as the videos for accurate temporal alignment.

Supports calibration-based drift compensation: use --calibration to load calibration
data generated by tools/calibrate_cameras.py, which applies per-camera delay and drift
corrections for improved synchronization.

Usage:
    python tools/create_sync_test_video.py --input data/sub-001/ses-001/video --output sync_test.mp4
    python tools/create_sync_test_video.py --input data/sub-001/ses-001/video --layout 2x1
    python tools/create_sync_test_video.py --input data/sub-001/ses-001/video --lsl-prefix ffmpeg_progress_
    python tools/create_sync_test_video.py --input data/sub-001/ses-001/video --dpa-audio dpa_an1_aud
    python tools/create_sync_test_video.py --input data/sub-001/ses-001/video --dpa-audio dpa_mic9_aud
    python tools/create_sync_test_video.py --input data/sub-001/ses-001/video --calibration calibration.json --dpa-audio 2
"""

import argparse
import csv
import json
import subprocess
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

import cv2
import numpy as np


@dataclass
class CameraCalibration:
    """Calibration data for a single camera (loaded from calibration.json)."""
    label: str
    initial_delay_ms: float
    drift_rate_ms_per_min: float
    jitter_ms: float
    mean_frame_interval_ms: float
    total_frames: int
    calibration_duration_s: float
    reference_camera: str
    calibrated_at: str

    def correction_at_time(self, elapsed_seconds: float) -> float:
        """Calculate total correction needed at a given time (in ms)."""
        drift_correction = (elapsed_seconds / 60.0) * self.drift_rate_ms_per_min
        return self.initial_delay_ms + drift_correction


def load_calibration(path: Path) -> dict | None:
    """Load calibration data from JSON file.
    
    Returns:
        Dictionary with 'cameras' (dict[str, CameraCalibration]), 
        'reference_camera', 'recommended_cfr', or None if not found.
    """
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text())
        cameras = {
            k: CameraCalibration(**v)
            for k, v in data.get("cameras", {}).items()
        }
        return {
            "cameras": cameras,
            "reference_camera": data.get("reference_camera"),
            "recommended_cfr": data.get("recommended_cfr"),
            "calibrated_at": data.get("calibrated_at"),
        }
    except Exception as e:
        print(f"Warning: Failed to load calibration from {path}: {e}")
        return None


def apply_calibration_corrections(
    start_times: dict[Path, float],
    video_files: list[Path],
    calibration: dict,
    durations: dict[Path, float],
) -> dict[Path, float]:
    """Apply calibration DRIFT corrections to start times.

    NOTE: Only applies drift correction, NOT initial delay offset.
    The initial offset is already handled by frame-log or LSL alignment.
    Calibration drift compensation corrects for clock skew over recording duration.

    Args:
        start_times: Current start times per video (already aligned by frame logs)
        video_files: List of video file paths
        calibration: Calibration data loaded from calibration.json
        durations: Per-video durations for drift calculation

    Returns:
        Corrected start times with drift compensation
    """
    if not calibration or "cameras" not in calibration:
        return start_times

    cameras = calibration["cameras"]
    corrected = {}

    for vf in video_files:
        label = vf.stem
        if label.endswith("_video"):
            label = label[: -len("_video")]

        base_time = start_times.get(vf, 0.0)

        if label in cameras:
            cal = cameras[label]
            duration = durations.get(vf, 0.0)
            # Only apply DRIFT correction (not initial_delay, which is already in frame logs)
            # Calculate drift at recording midpoint for best average accuracy
            drift_correction_ms = (duration / 2.0 / 60.0) * cal.drift_rate_ms_per_min
            # Convert ms to seconds
            corrected[vf] = base_time + (drift_correction_ms / 1000.0)
            print(f"  Drift correction for {label}: {drift_correction_ms:+.2f}ms (rate: {cal.drift_rate_ms_per_min:.1f}ms/min)")
        else:
            corrected[vf] = base_time

    return corrected


def load_first_lsl_timestamp(lsl_path: Path) -> tuple[float, float, float | None] | None:
    """Return the first LSL timestamp, frame number, and media_time_us (if present).

    Handles three stream formats emitted by ffmpeg_multicap:
    - 5-channel (current):  [out_time_sec, media_time_us, frame, drop_frames, dup_frames]
    - 4-channel (old):      [out_time_sec, frame, drop_frames, dup_frames]
    - 3-channel (legacy):   [lsl_time, media_time_us, frame]

    Returns:
        (stream_time, frame_number, media_time_us) or None if not found
    """
    try:
        with lsl_path.open("r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                data = json.loads(line)
                stream_time = float(data.get("stream_time"))
                values = data.get("values", [])
                if len(values) >= 5:
                    # Current 5-channel: [out_time_sec, media_time_us, frame, drop, dup]
                    media_time_us = float(values[1])
                    frame_number = float(values[2])
                elif len(values) == 4:
                    # Old 4-channel: [out_time_sec, frame, drop, dup] — no explicit media_time_us.
                    # Derive it from out_time_sec so the start anchor is still valid.
                    media_time_us = float(values[0]) * 1_000_000
                    frame_number = float(values[1])
                elif len(values) >= 3:
                    # Legacy 3-channel anchor stream: [lsl_time, media_time_us, frame]
                    media_time_us = float(values[1])
                    frame_number = float(values[2])
                else:
                    media_time_us = None
                    frame_number = float(values[1]) if len(values) > 1 else 0.0
                return (stream_time, frame_number, media_time_us)
    except Exception:
        return None
    return None


def load_lsl_anchor_candidates(lsl_path: Path) -> list[float]:
    """Load all (stream_time - out_time_sec) anchor candidates from an LSL JSONL file.

    Equivalent to load_progress_anchor_candidates but reads from the LSL JSONL
    instead of the TSV.  Works with all progress stream formats (3, 4, or 5
    channels) because values[0] is always out_time_sec in every format.
    Results can be combined with TSV candidates for a joint median.
    """
    candidates: list[float] = []
    try:
        segments: list[list[float]] = [[]]
        prev_out_time: float | None = None
        with lsl_path.open("r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    data = json.loads(line)
                    stream_time = float(data.get("stream_time", 0))
                    values = data.get("values", [])
                    if not values:
                        continue
                    out_time_sec = float(values[0])  # always index 0 in all formats
                    if prev_out_time is not None and out_time_sec + 0.5 < prev_out_time:
                        segments.append([])  # new run detected
                    segments[-1].append(stream_time - out_time_sec)
                    prev_out_time = out_time_sec
                except Exception:
                    continue
        for segment in reversed(segments):
            if segment:
                candidates.extend(segment)
                break
    except Exception:
        pass
    return candidates


def load_frame_log_start_estimate(
    frame_log: Path, max_samples: int = 30, min_valid: int = 3
) -> float | None:
    """Estimate video start unix time from frame log samples.

    Computes start_time = unix_time - pts_time across multiple samples and
    returns the median to reduce jitter. Returns None if insufficient samples.
    """
    starts: list[float] = []
    try:
        with frame_log.open("r", encoding="utf-8") as f:
            for line in f:
                if len(starts) >= max_samples:
                    break
                line = line.strip()
                if not line:
                    continue
                data = json.loads(line)
                try:
                    pts_time = float(data.get("pts_time"))
                    unix_time = float(data.get("unix_time_s", data.get("unix_time", 0)))
                except (TypeError, ValueError):
                    continue
                if unix_time <= 0:
                    continue
                starts.append(unix_time - pts_time)
    except Exception:
        return None

    if len(starts) < min_valid:
        return None

    starts.sort()
    mid = len(starts) // 2
    if len(starts) % 2 == 1:
        return starts[mid]
    return (starts[mid - 1] + starts[mid]) / 2.0


def load_frame_log_start_and_mad(
    frame_log: Path, max_samples: int = 30, min_valid: int = 3
) -> tuple[float | None, float | None]:
    """Return (median_start, MAD) from frame log samples.

    MAD is median absolute deviation of (unix_time - pts_time) samples,
    giving a robustness measure of the anchor quality.
    """
    starts: list[float] = []
    try:
        with frame_log.open("r", encoding="utf-8") as f:
            for line in f:
                if len(starts) >= max_samples:
                    break
                line = line.strip()
                if not line:
                    continue
                data = json.loads(line)
                try:
                    pts_time = float(data.get("pts_time"))
                    unix_time = float(data.get("unix_time_s", data.get("unix_time", 0)))
                except (TypeError, ValueError):
                    continue
                if unix_time <= 0:
                    continue
                starts.append(unix_time - pts_time)
    except Exception:
        return (None, None)

    if len(starts) < min_valid:
        return (None, None)

    starts.sort()
    mid = len(starts) // 2
    if len(starts) % 2 == 1:
        median = starts[mid]
    else:
        median = (starts[mid - 1] + starts[mid]) / 2.0

    # Compute MAD
    deviations = [abs(s - median) for s in starts]
    deviations.sort()
    dmid = len(deviations) // 2
    if len(deviations) % 2 == 1:
        mad = deviations[dmid]
    else:
        mad = (deviations[dmid - 1] + deviations[dmid]) / 2.0
    return (median, mad)


def compute_lsl_starts(
    input_files: list[Path], lsl_dir: Path, lsl_prefix: str, fps_map: dict[Path, float]
) -> dict[Path, float]:
    """Compute per-video start times (seconds) from LSL JSONL files."""
    frame_zero_timestamps: dict[Path, float] = {}

    for video in input_files:
        label = video.stem
        if label.endswith("_video"):
            label = label[: -len("_video")]

        candidates = [
            lsl_dir / f"{lsl_prefix}{label}.jsonl",
            lsl_dir / f"ffmpeg_progress_{label}.jsonl",
            lsl_dir / f"{label}.jsonl",
        ]
        lsl_path = next((p for p in candidates if p.exists()), None)
        if not lsl_path:
            continue

        result = load_first_lsl_timestamp(lsl_path)
        if result is not None:
            stream_time, frame_number, media_time_us = result
            if media_time_us is not None:
                # Anchor streams: start time is lsl_time - media_time
                frame_zero_time = stream_time - (media_time_us / 1_000_000)
            else:
                fps = fps_map.get(video, 30.0)
                frame_zero_time = stream_time - (frame_number / fps)
            frame_zero_timestamps[video] = frame_zero_time

    if not frame_zero_timestamps:
        return {}

    return frame_zero_timestamps


def compute_frame_log_starts(
    input_files: list[Path], frame_dir: Path, frame_log_samples: int = 30
) -> dict[Path, float]:
    """Compute per-video start times from showinfo frame logs.

    Uses unix_time (wall-clock anchor) from multiple logged frames to establish
    a global time reference, then estimates pts_time=0 per video via median.
    This reduces timing jitter compared to a single-sample anchor.
    """
    video_start_unix: dict[Path, float] = {}

    for video in input_files:
        label = video.stem
        if label.endswith("_video"):
            label = label[: -len("_video")]

        candidates = [frame_dir / f"{label}_frames.jsonl"]
        frame_path = next((p for p in candidates if p.exists()), None)
        if not frame_path:
            continue

        start_estimate = load_frame_log_start_estimate(frame_path, frame_log_samples)
        if start_estimate is not None:
            video_start_unix[video] = start_estimate

    if not video_start_unix:
        return {}

    return video_start_unix


def load_progress_anchor_candidates(session_dir: Path, label: str) -> list[float]:
    """Load (host_time - media_time) anchor candidates for one device label.

    Supports current TSV progress logs under sourcedata/sync and legacy JSONL
    progress logs under progress_logs.
    """
    candidates: list[float] = []

    tsv_path = session_dir / "sourcedata" / "sync" / f"{label}_ffmpeg_progress.tsv"
    if tsv_path.exists():
        segments: list[list[float]] = [[]]
        prev_out_time: float | None = None
        try:
            with tsv_path.open("r", encoding="utf-8") as f:
                reader = csv.DictReader(f, delimiter="\t")
                for row in reader:
                    try:
                        host_time = float(row["host_time_sec"])
                        out_time = float(row["out_time_sec"])
                    except (TypeError, ValueError, KeyError):
                        continue
                    # A large out_time drop means a new run in the same file.
                    if prev_out_time is not None and out_time + 0.5 < prev_out_time:
                        segments.append([])
                    segments[-1].append(host_time - out_time)
                    prev_out_time = out_time
            for segment in reversed(segments):
                if segment:
                    candidates.extend(segment)
                    break
        except Exception:
            pass

    legacy_path = session_dir / "progress_logs" / f"{label}_progress.jsonl"
    if legacy_path.exists():
        try:
            with legacy_path.open("r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    rec = json.loads(line)
                    media_time_us = rec.get("media_time_us")
                    lsl_time = rec.get("lsl_time")
                    if media_time_us is None or lsl_time is None:
                        continue
                    candidates.append(float(lsl_time) - (float(media_time_us) / 1_000_000))
        except Exception:
            pass

    return candidates


def _list_median(values: list[float]) -> float | None:
    """Return median of a non-empty list, or None."""
    if not values:
        return None
    vs = sorted(values)
    m = len(vs) // 2
    return vs[m] if len(vs) % 2 else (vs[m - 1] + vs[m]) / 2.0


def compute_dpa_shift(
    dpa_label: str,
    video_labels: list[str],
    session_dir: Path,
    lsl_dir: Path,
    lsl_prefix: str,
    event_path: Path,
    align_to: str = "latest",
) -> tuple[float, str] | tuple[None, None]:
    """Compute the trim/pad shift (seconds) for a DPA audio-only device.

    All comparisons are done within a single shared clock so clocks are never
    mixed.  Three tiers, tried in order:

    1. LSL JSONL  (lsl/{lsl_prefix}{label}.jsonl)
       Uses median(stream_time - out_time_sec) over all records for both DPA
       and each video.  stream_time is local_clock() at push time — the same
       shared LSL clock across all ffmpeg_multicap processes on the same host.
       Preferred because records are pushed at 10 Hz (-stats_period 0.1s),
       giving a robust median.

    2. Progress TSV  (sourcedata/sync/{label}_ffmpeg_progress.tsv)
       Uses median(host_time_sec - out_time_sec).  host_time_sec is
       local_clock() — identical clock to Tier 1.  Fallback when LSL files
       are absent (e.g. --record-lsl not passed during capture).

    3. Events JSONL  (video/ffmpeg_multicap_events.jsonl)
       capture_started unix timestamps.  Less accurate (~ms) but shared.

    Returns (shift_seconds, source_name) or (None, None) if no anchor.
    """
    # ---- Tier 1: LSL JSONL (multi-sample median, shared LSL clock) ----
    def _lsl_path(label: str) -> Path | None:
        for p in [lsl_dir / f"{lsl_prefix}{label}.jsonl", lsl_dir / f"{label}.jsonl"]:
            if p.exists():
                return p
        return None

    def _lsl_median(label: str) -> float | None:
        p = _lsl_path(label)
        if p is None:
            return None
        return _list_median(load_lsl_anchor_candidates(p))

    dpa_lsl = _lsl_median(dpa_label)
    if dpa_lsl is not None:
        vid_lsl = {lbl: t for lbl in video_labels if (t := _lsl_median(lbl)) is not None}
        if vid_lsl:
            ref = max(vid_lsl.values()) if align_to == "latest" else min(vid_lsl.values())
            # Positive = DPA started earlier (trim audio start)
            # Negative = DPA started later  (pad audio start with silence)
            shift = ref - dpa_lsl
            return shift, "lsl"

    # ---- Tier 2: Progress TSV (same local_clock() — fallback when LSL absent) ----
    dpa_cands = load_progress_anchor_candidates(session_dir, dpa_label)
    dpa_t = _list_median(dpa_cands)
    if dpa_t is not None:
        vid_ts: dict[str, float] = {}
        for lbl in video_labels:
            t = _list_median(load_progress_anchor_candidates(session_dir, lbl))
            if t is not None:
                vid_ts[lbl] = t
        if vid_ts:
            ref = max(vid_ts.values()) if align_to == "latest" else min(vid_ts.values())
            shift = ref - dpa_t
            return shift, "progress_tsv"

    # ---- Tier 3: capture_started events (unix timestamps) ----
    if event_path.exists():
        try:
            ev_starts: dict[str, list[float]] = {}
            with event_path.open("r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    rec = json.loads(line)
                    if rec.get("event_type") != "capture_started":
                        continue
                    dev = rec.get("device_id", "")
                    if dev not in video_labels and dev != dpa_label:
                        continue
                    ts_str = rec.get("timestamp", "")
                    try:
                        ts = float(rec["unix_time_s"]) if "unix_time_s" in rec else datetime.fromisoformat(ts_str).timestamp()
                    except Exception:
                        continue
                    ev_starts.setdefault(dev, []).append(ts)
            # Use the latest run for every device
            latest_run = {dev: tss[-1] for dev, tss in ev_starts.items()}
            dpa_ev = latest_run.get(dpa_label)
            vid_ev = {lbl: latest_run[lbl] for lbl in video_labels if lbl in latest_run}
            if dpa_ev is not None and vid_ev:
                ref = max(vid_ev.values()) if align_to == "latest" else min(vid_ev.values())
                shift = ref - dpa_ev
                return shift, "events"
        except Exception:
            pass

    return None, None


def detect_content_onset(
    video_path: Path,
    fps: float,
    max_seconds: float = 12.0,
    threshold_k: float = 6.0,
    sustain_frames: int = 5,
) -> float | None:
    """Detect content onset time (seconds) by frame-difference spikes.

    Computes per-frame grayscale difference and finds the first sustained spike
    above baseline. Returns onset time in seconds, or None if not detected.
    """
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        return None

    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    sample_frames = int(min(total_frames, max_seconds * (fps or 30.0)))
    prev = None
    diffs: list[float] = []
    for _i in range(sample_frames):
        ret, frame = cap.read()
        if not ret:
            break
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        gray = cv2.resize(gray, (320, 180))
        if prev is None:
            prev = gray
            diffs.append(0.0)
            continue
        diff = np.mean(np.abs(gray.astype(np.float32) - prev.astype(np.float32)))
        diffs.append(float(diff))
        prev = gray
    cap.release()

    if len(diffs) < max(10, sustain_frames + 1):
        return None

    baseline_window = int(max(1, fps))  # ~1s baseline
    baseline = float(np.median(diffs[:baseline_window]))
    mad = float(np.median(np.abs(np.array(diffs[:baseline_window]) - baseline)))
    thresh = baseline + threshold_k * (mad if mad > 0 else 1.0)

    # Find first sustained exceedance
    for idx in range(baseline_window, len(diffs) - sustain_frames):
        window = diffs[idx:idx + sustain_frames]
        if all(v > thresh for v in window):
            return idx / (fps or 30.0)
    return None


def compute_content_starts(
    input_files: list[Path], fps_map: dict[Path, float], max_seconds: float, threshold_k: float, sustain_frames: int
) -> dict[Path, float]:
    """Compute per-video content onset times via frame-difference spikes."""
    starts: dict[Path, float] = {}
    for vf in input_files:
        onset = detect_content_onset(vf, fps_map.get(vf, 30.0), max_seconds, threshold_k, sustain_frames)
        if onset is not None:
            starts[vf] = onset
    return starts


def compute_event_starts(input_files: list[Path], event_path: Path) -> dict[Path, float]:
    """Compute start times from ffmpeg_multicap_events.jsonl (capture_started timestamps)."""
    if not event_path.exists():
        return {}

    starts: dict[str, float] = {}
    try:
        with event_path.open("r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                rec = json.loads(line)
                if rec.get("event_type") != "capture_started":
                    continue
                ts_str = rec.get("timestamp")
                device_id = rec.get("device_id")
                if not ts_str or not device_id:
                    continue
                try:
                    if "unix_time_s" in rec:
                        ts = float(rec["unix_time_s"])
                    else:
                        ts = datetime.fromisoformat(ts_str).timestamp()
                except Exception:
                    continue
                if device_id not in starts:
                    starts[device_id] = ts
    except Exception:
        return {}

    if not starts:
        return {}

    offsets: dict[Path, float] = {}
    for video in input_files:
        label = video.stem
        if label.endswith("_video"):
            label = label[: -len("_video")]
        if label in starts:
            offsets[video] = starts[label]
    return offsets


def compute_alignment_shifts(
    start_times: dict[Path, float], align_to: str
) -> dict[Path, float]:
    """Compute per-video shifts (seconds) for trim/pad alignment."""
    if not start_times:
        return {}

    if align_to == "earliest":
        base = min(start_times.values())
        return {video: max(0.0, ts - base) for video, ts in start_times.items()}

    base = max(start_times.values())
    return {video: max(0.0, base - ts) for video, ts in start_times.items()}


def find_dpa_audio_file(audio_dir: Path, label: str) -> Path | None:
    """Find DPA audio file by device label (e.g., 'dpa_an1_aud', 'dpa_mic9_aud').

    Tries common naming variants: {label}.wav and {label}_aud.wav.
    Returns None if not found; prints available DPA files for diagnostics.
    """
    if not audio_dir.exists():
        print(f"[WARN] Audio directory not found: {audio_dir}")
        return None

    # Try common naming patterns
    patterns = [
        f"{label}.wav",
        f"{label}_aud.wav",
    ]

    for pattern in patterns:
        candidate = audio_dir / pattern
        if candidate.exists():
            return candidate

    # Not found — show available DPA-looking files for guidance
    available = sorted(p.name for p in audio_dir.glob("*.wav") if "dpa" in p.name.lower())
    if available:
        print(f"[WARN] No audio file found for label '{label}' in {audio_dir}")
        print(f"  Available DPA files: {', '.join(available)}")
        print("  Hint: pass the filename without extension as --dpa-audio")
    else:
        print(f"[WARN] No DPA audio files found in {audio_dir}")
    return None


def create_grid_video(
    input_files: list[Path],
    output_file: Path,
    layout: str = "2x2",
    shifts: dict[Path, float] | None = None,
    tail_pads: dict[Path, float] | None = None,
    align_to: str = "latest",
    dpa_audio_file: Path | None = None,
    dpa_shift: float = 0.0,
    dpa_tail_pad: float = 0.0,
) -> bool:
    """Create a grid layout video from multiple input videos using ffmpeg.
    
    Args:
        input_files: List of video file paths to combine
        output_file: Output video file path
        layout: Grid layout (e.g., "2x2", "2x1", "3x1")
        shifts: Optional per-file start offsets (seconds) to align streams
        tail_pads: Optional per-file tail pad durations (seconds) for shorter videos
        align_to: Alignment target ("latest" or "earliest")
        dpa_audio_file: Optional DPA microphone audio file to mix in
        dpa_shift: Shift for DPA audio (seconds)
        dpa_tail_pad: Tail pad for DPA audio (seconds)
    
    Returns:
        True if successful, False otherwise
    """
    if not input_files:
        print("No input files provided")
        return False

    # Parse layout (e.g., "2x2" -> cols=2, rows=2)
    try:
        cols, rows = map(int, layout.lower().split('x'))
    except ValueError:
        print(f"Invalid layout format: {layout}. Use format like '2x2' or '2x1'")
        return False

    max_videos = cols * rows
    if len(input_files) > max_videos:
        print(f"Warning: Layout {layout} supports max {max_videos} videos, using first {max_videos}")
        input_files = input_files[:max_videos]

    # Build ffmpeg filter for grid layout
    # Each video is scaled and then combined into a grid
    filter_parts = []

    # Scale inputs (preserve aspect ratio with padding)
    shifts = shifts or {}
    scaled_width = 960
    scaled_height = 540

    for i in range(len(input_files)):
        shift = shifts.get(input_files[i], 0.0)
        tail_pad = 0.0
        if tail_pads:
            tail_pad = float(tail_pads.get(input_files[i], 0.0))
        align_chain = ""
        if align_to == "latest" and shift > 0:
            align_chain = f"trim=start={shift:.6f},"
        if align_to == "earliest" and shift > 0:
            align_chain = f"tpad=start_duration={shift:.6f}:color=black,"
        tail_chain = ""
        if tail_pad > 0:
            tail_chain = f",tpad=stop_duration={tail_pad:.6f}:color=black"
        filter_parts.append(
            f"[{i}:v]{align_chain}setpts=PTS-STARTPTS,"
            f"scale={scaled_width}:{scaled_height}:force_original_aspect_ratio=decrease,"
            f"pad={scaled_width}:{scaled_height}:(ow-iw)/2:(oh-ih)/2{tail_chain}[v{i}]"
        )

    # Create grid using xstack
    if len(input_files) == 1:
        filter_complex = f"{filter_parts[0]}"
        map_output = "[v0]"
    elif len(input_files) == 2 and layout == "2x1":
        # Side by side
        filter_parts.append("[v0][v1]hstack=inputs=2[v]")
        filter_complex = ";".join(filter_parts)
        map_output = "[v]"
    elif len(input_files) == 2 and layout == "1x2":
        # Top and bottom
        filter_parts.append("[v0][v1]vstack=inputs=2[v]")
        filter_complex = ";".join(filter_parts)
        map_output = "[v]"
    else:
        # Grid layout using xstack with absolute pixel positions
        # Calculate positions based on scaled dimensions
        layout_str = ""
        for row in range(rows):
            for col in range(cols):
                idx = row * cols + col
                if idx >= len(input_files):
                    break
                if layout_str:
                    layout_str += "|"
                x = col * scaled_width
                y = row * scaled_height
                layout_str += f"{x}_{y}"

        inputs_str = "".join(f"[v{i}]" for i in range(len(input_files)))
        filter_parts.append(f"{inputs_str}xstack=inputs={len(input_files)}:layout={layout_str}[v]")
        filter_complex = ";".join(filter_parts)
        map_output = "[v]"

    # Build audio chain if DPA audio provided
    audio_chain_parts = []
    last_audio_index = len(input_files)
    map_audio = None
    
    if dpa_audio_file and dpa_audio_file.exists():
        # Build audio filter for DPA: apply synchronization matching video alignment
        dpa_audio_label = f"[{last_audio_index}:a]"
        audio_align_chain = ""
        # dpa_shift > 0  -> audio started earlier than video ref -> trim
        # dpa_shift < 0  -> audio started later  than video ref -> pad
        if dpa_shift > 0:
            audio_align_chain = f"atrim=start={dpa_shift:.6f},"
        elif dpa_shift < 0:
            # For mono audio, use single delay value (not stereo |pipe| syntax)
            audio_align_chain = f"adelay={int(abs(dpa_shift) * 1000)},"
        
        dpa_audio_tail = ""
        if dpa_tail_pad > 0:
            dpa_audio_tail = f",apad=pad_dur={dpa_tail_pad:.6f}"
        
        # DPA audio processing with normalization
        audio_chain_parts.append(
            f"{dpa_audio_label}{audio_align_chain}"
            f"aformat=sample_rates=48000:channel_layouts=mono"
            f"{dpa_audio_tail}[dpa_audio]"
        )
        
        if filter_complex:
            filter_complex += ";"
        filter_complex += ";".join(audio_chain_parts)
        map_audio = "[dpa_audio]"
    
    # Build ffmpeg command
    cmd = ["ffmpeg"]

    for input_file in input_files:
        cmd.extend(["-i", str(input_file)])
    
    if dpa_audio_file and dpa_audio_file.exists():
        cmd.extend(["-i", str(dpa_audio_file)])

    cmd.extend([
        "-filter_complex", filter_complex,
        "-map", map_output,
    ])
    
    if map_audio:
        cmd.extend(["-map", map_audio])
    
    cmd.extend([
        "-c:v", "mpeg4",
        "-q:v", "3",
        "-pix_fmt", "yuv420p",
    ])
    if map_audio:
        cmd.extend(["-c:a", "aac", "-b:a", "128k"])
    cmd.extend(["-y", str(output_file)])

    print(f"\nCreating {layout} grid video from {len(input_files)} inputs...")
    if dpa_audio_file and dpa_audio_file.exists():
        print(f"  With DPA audio: {dpa_audio_file.name} (shift={dpa_shift:+.3f}s)")
    print(f"Command: {' '.join(cmd)}")

    try:
        subprocess.run(cmd, check=True)
        print(f"[OK] Sync test video created: {output_file}")
        print(f"  Size: {output_file.stat().st_size / (1024*1024):.1f} MB")
        
        # Write sync diagnostics file for debugging
        diagnostics_file = output_file.with_suffix('.sync_diagnostics.json')
        try:
            diagnostics = {
                "output_video": str(output_file),
                "created_at": datetime.now().isoformat(),
                "layout": layout,
                "align_to": align_to,
                "num_videos": len(input_files),
                "videos": [
                    {
                        "file": str(vf),
                        "label": vf.stem,
                        "shift_seconds": float(shifts.get(vf, 0.0)) if shifts else 0.0,
                        "tail_pad_seconds": float(tail_pads.get(vf, 0.0)) if tail_pads else 0.0,
                    }
                    for vf in input_files
                ],
                "dpa_audio": {
                    "file": str(dpa_audio_file) if dpa_audio_file else None,
                    "shift_seconds": float(dpa_shift),
                    "tail_pad_seconds": float(dpa_tail_pad),
                    "operation": "trim" if dpa_shift > 0 else "pad" if dpa_shift < 0 else "none",
                } if dpa_audio_file else None,
                "ffmpeg_command": cmd,
            }
            diagnostics_file.write_text(json.dumps(diagnostics, indent=2))
            print(f"  Diagnostics: {diagnostics_file}")
        except Exception as e:
            print(f"  [WARN] Could not write diagnostics file: {e}")
        
        return True
    except subprocess.CalledProcessError as e:
        print(f"[ERROR] ffmpeg failed: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(
        description="Create synchronized multi-view test video from captured streams"
    )
    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help="Input directory containing video files (e.g., data/sub-001/ses-001/video)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("sync_test.mp4"),
        help="Output video file path (default: sync_test.mp4)",
    )
    parser.add_argument(
        "--layout",
        type=str,
        default="2x2",
        help="Grid layout: 2x2, 2x1, 1x2, 3x1, etc. (default: 2x2)",
    )
    parser.add_argument(
        "--pattern",
        type=str,
        default="*_video.mkv",
        help="File pattern to match (default: *_video.mkv)",
    )
    parser.add_argument(
        "--frame-log-samples",
        type=int,
        default=30,
        help="Number of frame-log samples to estimate start time (default: 30)",
    )
    parser.add_argument(
        "--lsl-dir",
        type=Path,
        default=None,
        help="Directory containing LSL JSONL streams (default: <input>/../lsl)",
    )
    parser.add_argument(
        "--lsl-prefix",
        type=str,
        default="ffmpeg_progress_",
        help="Prefix for LSL stream files (default: ffmpeg_progress_)",
    )
    parser.add_argument(
        "--no-lsl-sync",
        action="store_true",
        help="Disable LSL-based alignment and just stack videos",
    )
    parser.add_argument(
        "--cfr",
        type=float,
        default=None,
        help="Force constant frame rate on output (e.g., 30)",
    )
    parser.add_argument(
        "--overwrite-output",
        action="store_true",
        help="Overwrite the original output with CFR version (Windows-safe: attempts unlink first)",
    )
    parser.add_argument(
        "--use-events",
        action="store_true",
        help="If no frame logs/LSL are available, align using capture start offsets from ffmpeg_multicap_events.jsonl",
    )
    parser.add_argument(
        "--source",
        type=str,
        default=None,
        choices=["frame", "lsl", "events", "best", "content"],
        help="Explicitly choose alignment source (frame, lsl, events, best, or content). Default: auto fallback",
    )
    parser.add_argument(
        "--content-threshold-k",
        type=float,
        default=6.0,
        help="Threshold multiplier (k * MAD) for content onset detection (default: 6.0)",
    )
    parser.add_argument(
        "--content-sustain-frames",
        type=int,
        default=5,
        help="Sustain frames required above threshold for onset (default: 5)",
    )
    parser.add_argument(
        "--content-max-seconds",
        type=float,
        default=12.0,
        help="Max seconds to scan for content onset (default: 12.0)",
    )
    parser.add_argument(
        "--offset",
        type=str,
        default=None,
        help="Manual per-label start time overrides (comma-separated label=seconds). Negative trims earlier (e.g., jabra_panacast_20_vid=-2.0)",
    )
    parser.add_argument(
        "--use-compare-offsets",
        action="store_true",
        help="Compute per-device offsets from progress/anchor logs (median delay) and apply automatically",
    )
    parser.add_argument(
        "--align-to",
        type=str,
        default="latest",
        choices=["latest", "earliest"],
        help="Align to the latest or earliest stream start (default: latest)",
    )
    parser.add_argument(
        "--pad-tail",
        action="store_true",
        help="Zero-mask shorter videos by padding the tail with black",
    )
    parser.add_argument(
        "--calibration",
        type=Path,
        default=None,
        help="Path to calibration.json from calibrate_cameras.py for drift compensation",
    )
    parser.add_argument(
        "--dpa-audio",
        type=str,
        default=None,
        metavar="LABEL",
        help="Include DPA microphone audio by device label (e.g. dpa_an1_aud, dpa_mic9_aud). "
             "Pass the WAV filename without extension from <input>/../audio/.",
    )
    parser.add_argument(
        "--dpa-audio-dir",
        type=Path,
        default=None,
        help="Directory containing DPA audio files (default: <input>/../audio)",
    )
    parser.add_argument(
        "--dpa-audio-offset",
        type=float,
        default=0.0,
        metavar="SECONDS",
        help="Additive correction to the computed DPA shift (seconds). "
             "Use a negative value to reduce the trim when audio sounds late (e.g. -0.1).",
    )

    args = parser.parse_args()

    # Find video files
    if not args.input.exists():
        print(f"Input directory not found: {args.input}")
        return 1

    video_files = sorted(args.input.glob(args.pattern))
    if not video_files:
        print(f"No video files matching pattern '{args.pattern}' found in {args.input}")
        return 1

    print(f"Found {len(video_files)} video files:")
    for vf in video_files:
        print(f"  - {vf.name}")

    shifts: dict[Path, float] | None = None
    start_times: dict[Path, float] | None = None
    offset_source = None

    # Probe per-file FPS and durations via ffprobe
    def _parse_fraction(s: str) -> float | None:
        try:
            if "/" in s:
                a, b = s.split("/", 1)
                if float(b) == 0:
                    return None
                return float(a) / float(b)
            return float(s)
        except Exception:
            return None

    def ffprobe_fps(p: Path) -> float | None:
        try:
            out = subprocess.check_output(
                [
                    "ffprobe",
                    "-v",
                    "error",
                    "-select_streams",
                    "v:0",
                    "-show_entries",
                    "stream=avg_frame_rate",
                    "-of",
                    "default=nw=1:nk=1",
                    str(p),
                ],
                text=True,
            ).strip()
            return _parse_fraction(out)
        except Exception:
            return None

    def ffprobe_duration(p: Path) -> float | None:
        try:
            out = subprocess.check_output(
                [
                    "ffprobe",
                    "-v",
                    "error",
                    "-show_entries",
                    "format=duration",
                    "-of",
                    "default=nw=1:nk=1",
                    str(p),
                ],
                text=True,
            ).strip()
            return float(out)
        except Exception:
            return None

    fps_map: dict[Path, float] = {}
    durations: dict[Path, float] = {}
    for vf in video_files:
        fps_map[vf] = ffprobe_fps(vf) or 30.0
        durations[vf] = ffprobe_duration(vf) or 0.0

    print("Probed FPS (Hz) and durations (s):")
    for vf in video_files:
        print(f"  - {vf.stem}: fps={fps_map[vf]:.5g}, dur={durations[vf]:.3f}")

    # Load calibration if provided
    calibration = None
    if args.calibration:
        calibration = load_calibration(args.calibration)
        if calibration:
            print(f"\n[OK] Loaded calibration from {args.calibration}")
            print(f"  Reference camera: {calibration.get('reference_camera')}")
            print(f"  Calibrated at: {calibration.get('calibrated_at')}")
            if calibration.get('recommended_cfr') and not args.cfr:
                print(f"  Recommended CFR: {calibration.get('recommended_cfr')} fps")
        else:
            print(f"[WARN] Could not load calibration from {args.calibration}")

    if not args.no_lsl_sync:
        frame_dir = args.input.parent / "frame_logs"
        lsl_dir = args.lsl_dir or args.input.parent / "lsl"
        event_path = args.input / "ffmpeg_multicap_events.jsonl"
        # Explicit source selection if requested
        if args.source == "frame":
            if frame_dir.exists():
                start_times = compute_frame_log_starts(
                    video_files, frame_dir, frame_log_samples=args.frame_log_samples
                )
                offset_source = "frame_logs" if start_times else None
        elif args.source == "lsl":
            if lsl_dir.exists():
                start_times = compute_lsl_starts(video_files, lsl_dir, args.lsl_prefix, fps_map)
                offset_source = "lsl" if start_times else None
        elif args.source == "events":
            start_times = compute_event_starts(video_files, event_path)
            offset_source = "events" if start_times else None
        elif args.source == "content":
            start_times = compute_content_starts(
                video_files,
                fps_map,
                max_seconds=args.content_max_seconds,
                threshold_k=args.content_threshold_k,
                sustain_frames=args.content_sustain_frames,
            )
            offset_source = "content" if start_times else None
        elif args.source == "best":
            # Prefer LSL anchors when available (media_time_us), else pick the source
            # with the smallest per-stream MAD of start estimates; fallback to events.
            lsl_times = compute_lsl_starts(video_files, lsl_dir, args.lsl_prefix, fps_map) if lsl_dir.exists() else {}
            if lsl_times:
                start_times = lsl_times
                offset_source = "lsl"
            else:
                # Compute frame starts and MADs
                frame_times: dict[Path, float] = {}
                frame_mads: dict[Path, float] = {}
                if frame_dir.exists():
                    for vf in video_files:
                        label = vf.stem[:-len("_video")] if vf.stem.endswith("_video") else vf.stem
                        fpath = frame_dir / f"{label}_frames.jsonl"
                        if not fpath.exists():
                            continue
                        median, mad = load_frame_log_start_and_mad(fpath, max_samples=args.frame_log_samples)
                        if median is not None:
                            frame_times[vf] = median
                            frame_mads[vf] = mad or 0.0
                if frame_times and len(frame_times) == len(video_files):
                    # Evaluate quality: pick if average MAD < 0.2s
                    avg_mad = sum(frame_mads.values()) / max(1, len(frame_mads))
                    start_times = frame_times
                    offset_source = "frame_logs"
                    print(f"Frame-log quality: avg MAD={avg_mad:.3f}s")
                else:
                    ev_times = compute_event_starts(video_files, event_path)
                    if ev_times:
                        start_times = ev_times
                        offset_source = "events"
                    else:
                        # As last resort, try content onset
                        content_times = compute_content_starts(
                            video_files,
                            fps_map,
                            max_seconds=args.content_max_seconds,
                            threshold_k=args.content_threshold_k,
                            sustain_frames=args.content_sustain_frames,
                        )
                        if content_times:
                            start_times = content_times
                            offset_source = "content"
                        else:
                            start_times = None
                            offset_source = None
        else:
            # Auto-fallback order: frame -> lsl -> events (if --use-events set)
            if frame_dir.exists():
                start_times = compute_frame_log_starts(
                    video_files, frame_dir, frame_log_samples=args.frame_log_samples
                )
                if start_times:
                    offset_source = "frame_logs"
            if (start_times is None or not start_times) and lsl_dir.exists():
                start_times = compute_lsl_starts(video_files, lsl_dir, args.lsl_prefix, fps_map)
                if start_times:
                    offset_source = "lsl"
            if (start_times is None or not start_times) and args.use_events:
                start_times = compute_event_starts(video_files, event_path)
                if start_times:
                    offset_source = "events"

        if start_times:
            label_print = {
                vf: (vf.stem[:-len("_video")] if vf.stem.endswith("_video") else vf.stem)
                for vf in video_files
            }
            print(f"{offset_source.capitalize() if offset_source else 'Alignment'} start times (s):")
            for vf in video_files:
                delta = start_times.get(vf)
                print(
                    f"  - {label_print[vf]}: {delta:.3f}" if delta is not None else f"  - {label_print[vf]}: missing"
                )
        else:
            print("No alignment sources found; proceeding without alignment")

    # Manual per-label overrides (e.g., jabra_panacast_20_vid=-2.0 to trim 2s)
    if start_times and args.offset:
        overrides: dict[str, float] = {}
        try:
            for pair in args.offset.split(","):
                if not pair.strip():
                    continue
                name, val = pair.split("=", 1)
                overrides[name.strip()] = float(val.strip())
        except Exception:
            print("[WARN] Failed to parse --offset; expected comma-separated label=seconds entries")
            overrides = {}

        # Apply overrides by label
        for vf in video_files:
            label = vf.stem[:-len("_video")] if vf.stem.endswith("_video") else vf.stem
            if label in overrides:
                adj = overrides[label]
                start_times[vf] = (start_times.get(vf) or 0.0) + adj
                print(f"Override: {label} start += {adj:+.3f}s")

    if start_times:
        shifts = compute_alignment_shifts(start_times, args.align_to)
        print(f"Alignment shifts (s, align_to={args.align_to}):")
        for vf in video_files:
            delta = shifts.get(vf)
            label = vf.stem
            if label.endswith("_video"):
                label = label[: -len("_video")]
            print(f"  - {label}: {delta:+.3f}" if delta is not None else f"  - {label}: missing")

    # Apply calibration corrections if available
    if start_times and calibration:
        print("\nApplying calibration corrections:")
        start_times = apply_calibration_corrections(start_times, video_files, calibration, durations)
        shifts = compute_alignment_shifts(start_times, args.align_to)
        print(f"\nCalibration-adjusted shifts (s, align_to={args.align_to}):")
        for vf in video_files:
            delta = shifts.get(vf)
            label = vf.stem
            if label.endswith("_video"):
                label = label[: -len("_video")]
            print(f"  - {label}: {delta:+.3f}" if delta is not None else f"  - {label}: missing")

    # Optional: offsets from compare (anchor-based delays)
    if args.use_compare_offsets:
        session_dir = args.input.parent
        lsl_dir = args.lsl_dir or session_dir / "lsl"
        frame_dir = session_dir / "frame_logs"
        prefix = args.lsl_prefix

        def _anchor_candidates_for(label: str) -> list[float]:
            cands = load_progress_anchor_candidates(session_dir, label)
            # anchor lsl
            anc_path = lsl_dir / f"{prefix}{label}_anchor.jsonl"
            if anc_path.exists():
                try:
                    with anc_path.open("r", encoding="utf-8") as f:
                        for line in f:
                            line = line.strip()
                            if not line:
                                continue
                            rec = json.loads(line)
                            vals = rec.get("values", [])
                            if len(vals) >= 2:
                                lt = float(rec.get("stream_time", 0))
                                mt = float(vals[1])
                                cands.append(lt - (mt / 1_000_000))
                except Exception:
                    pass
            return cands

        def _median(values: list[float]) -> float | None:
            if not values:
                return None
            vs = sorted(values)
            m = len(vs) // 2
            if len(vs) % 2:
                return vs[m]
            return (vs[m - 1] + vs[m]) / 2.0

        # Compute per-label recommended offsets
        offsets_map: dict[str, float] = {}
        print("Compare-based offsets (s):")
        for vf in video_files:
            label = vf.stem
            if label.endswith("_video"):
                label = label[: -len("_video")]
            anchor_cands = _anchor_candidates_for(label)
            anchor_start = _median(anchor_cands)
            rec_offset = 0.0
            if anchor_start is not None:
                # build frame delays
                fpath = frame_dir / f"{label}_frames.jsonl"
                delays: list[float] = []
                try:
                    with fpath.open("r", encoding="utf-8") as f:
                        for line in f:
                            line = line.strip()
                            if not line:
                                continue
                            data = json.loads(line)
                            lsl_clock = float(data.get("lsl_time", data.get("lsl_clock", 0)))
                            pts_time = float(data.get("pts_time", 0))
                            delays.append(lsl_clock - (anchor_start + pts_time))
                except Exception:
                    pass
                med = _median(delays)
                if med is not None:
                    rec_offset = -float(med)
            offsets_map[label] = rec_offset
            print(f"  - {label}: {rec_offset:+.3f}")

        # Apply offsets to start_times before computing shifts
        if start_times:
            for vf in video_files:
                label = vf.stem
                if label.endswith("_video"):
                    label = label[: -len("_video")]
                if label in offsets_map:
                    start_times[vf] = (start_times.get(vf) or 0.0) + offsets_map[label]
            shifts = compute_alignment_shifts(start_times, args.align_to)
            print(f"Alignment shifts with compare offsets (s, align_to={args.align_to}):")
            for vf in video_files:
                delta = shifts.get(vf)
                label = vf.stem
                if label.endswith("_video"):
                    label = label[: -len("_video")]
                print(f"  - {label}: {delta:+.3f}" if delta is not None else f"  - {label}: missing")

    # Compute tail pads to zero-mask shorter videos
    tail_pads: dict[Path, float] | None = None
    if args.pad_tail and shifts:
        effective_durations: dict[Path, float] = {}
        for vf in video_files:
            shift = float(shifts.get(vf, 0.0))
            if args.align_to == "latest":
                effective_durations[vf] = max(0.0, durations[vf] - shift)
            else:
                effective_durations[vf] = durations[vf] + shift
        max_eff = max(effective_durations.values()) if effective_durations else 0.0
        tail_pads = {}
        print("Tail pad durations (s):")
        for vf in video_files:
            pad = max(0.0, max_eff - effective_durations.get(vf, 0.0))
            tail_pads[vf] = pad
            label = vf.stem
            if label.endswith("_video"):
                label = label[: -len("_video")]
            print(f"  - {label}: {pad:.3f}")

    # Create grid video
    dpa_audio_file = None
    dpa_shift = 0.0
    dpa_tail_pad = 0.0

    if args.dpa_audio:
        audio_dir = args.dpa_audio_dir or args.input.parent / "audio"
        dpa_audio_file = find_dpa_audio_file(audio_dir, args.dpa_audio)

        if dpa_audio_file:
            print(f"\n[OK] Found DPA audio: {dpa_audio_file.name}")

            dpa_label = dpa_audio_file.stem  # e.g. "dpa_an1_aud"
            _session_dir = args.input.parent
            _lsl_dir = args.lsl_dir or _session_dir / "lsl"
            _event_path = args.input / "ffmpeg_multicap_events.jsonl"

            # Build the list of video labels as used in progress TSV filenames
            video_labels_for_audio = [
                (vf.stem[: -len("_video")] if vf.stem.endswith("_video") else vf.stem)
                for vf in video_files
            ]

            computed_shift, shift_source = compute_dpa_shift(
                dpa_label,
                video_labels_for_audio,
                _session_dir,
                _lsl_dir,
                args.lsl_prefix,
                _event_path,
                args.align_to,
            )

            if computed_shift is not None:
                dpa_shift = computed_shift
                if args.dpa_audio_offset:
                    adjusted = dpa_shift + args.dpa_audio_offset
                    print(f"  DPA audio sync: shift={dpa_shift:+.3f}s (source: {shift_source}), "
                          f"offset={args.dpa_audio_offset:+.3f}s -> final={adjusted:+.3f}s")
                    dpa_shift = adjusted
                else:
                    direction = "trim" if dpa_shift > 0 else "pad" if dpa_shift < 0 else "none"
                    print(f"  DPA audio sync: shift={dpa_shift:+.3f}s [{direction}] (source: {shift_source})")
                    if dpa_shift > 0:
                        print(f"    -> Audio started {abs(dpa_shift):.3f}s BEFORE video ref, trimming {abs(dpa_shift):.3f}s from audio start")
                    elif dpa_shift < 0:
                        print(f"    -> Audio started {abs(dpa_shift):.3f}s AFTER video ref, adding {abs(dpa_shift):.3f}s silence before audio")
            else:
                print(f"  [WARN] No progress/LSL/events anchor found for '{dpa_label}'; "
                      "audio will not be trimmed")

            if tail_pads:
                dpa_tail_pad = max(tail_pads.values())
                if dpa_tail_pad > 0:
                    print(f"  DPA tail pad: {dpa_tail_pad:.3f}s")
        else:
            print(f"\n[WARN] Could not find DPA audio file for label '{args.dpa_audio}' in {audio_dir}")

    success = create_grid_video(
        video_files,
        args.output,
        args.layout,
        shifts=shifts,
        tail_pads=tail_pads,
        align_to=args.align_to,
        dpa_audio_file=dpa_audio_file,
        dpa_shift=dpa_shift,
        dpa_tail_pad=dpa_tail_pad,
    )

    # If CFR requested, re-encode enforcing CFR
    if success and args.cfr:
        tmp_out = args.output.with_name(args.output.stem + "_cfr.mp4")
        cmd = [
            "ffmpeg",
            "-i",
            str(args.output),
            "-vsync",
            "cfr",
            "-r",
            str(args.cfr),
            "-c:v", "mpeg4",
            "-q:v", "3",
            "-pix_fmt", "yuv420p",
            "-y",
            str(tmp_out),
        ]
        print("Re-encoding with CFR:")
        print(" ", " ".join(cmd))
        try:
            subprocess.run(cmd, check=True)
            if args.overwrite_output:
                try:
                    if args.output.exists():
                        args.output.unlink(missing_ok=True)
                    tmp_out.replace(args.output)
                    print("[OK] CFR enforced; replaced original output")
                except Exception as e:
                    print(f"[WARN] Could not replace original output: {e}")
                    print(f"  CFR file kept at {tmp_out}")
            else:
                print("[OK] CFR enforced; CFR file saved alongside original")
        except subprocess.CalledProcessError as e:
            print(f"[ERROR] CFR re-encode failed: {e}")
    return 0 if success else 1


if __name__ == "__main__":
    exit(main())
