#!/usr/bin/env python3
"""Generate a session-specific world-align YAML config for tobii_multi_glasses_world_align.py.

Scans the session et/ dir for scene videos and NDJSON files and writes the
devices block automatically. World geometry is read from the shared template.

Usage::

    python tools/generate_world_align_config.py \\
        --session-dir "F:/processed_data/sub-01/ses-20260318_grp-13_run01" \\
        --task T1 \\
        --template configs/tobii_offline_world_align.example.yaml \\
        --output   configs/tobii_offline_world_align_grp13_T1.yaml
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml


_TOBII_FX_DEFAULT = 1300.0  # approximate Tobii Glasses 3 scene-camera focal length


def _find_scene_videos(et_dir: Path, task: str) -> dict[str, Path]:
    """Return {participant_id: mp4_path} for BIDS Tobii scene video files."""
    result: dict[str, Path] = {}
    for p in sorted(et_dir.glob(f"*_task-{task}_run-*_acq-P*_tobii.mp4")):
        m = re.search(r"_acq-(P\d+)_tobii", p.name)
        if m:
            result[m.group(1)] = p
    return result


def _find_gaze_ndjsons(et_dir: Path, task: str) -> dict[str, Path]:
    """Return {participant_id: ndjson_path}."""
    result: dict[str, Path] = {}
    for p in sorted(et_dir.glob(f"P*_task-{task}_gaze.ndjson")):
        m = re.match(r"(P\d+)_task-", p.name)
        if m:
            result[m.group(1)] = p
    return result


def generate(
    session_dir: Path,
    task: str,
    template_path: Path,
    output_path: Path,
) -> None:
    """Generate the world-align config for a session/task."""
    et_dir = session_dir / "et"
    ses_name = session_dir.name  # e.g. ses-20260318_grp-13_run01

    scene_videos = _find_scene_videos(et_dir, task)
    gaze_ndjsons = _find_gaze_ndjsons(et_dir, task)

    if not scene_videos:
        print(f"WARNING: no scene videos found for task {task} in {et_dir}", file=sys.stderr)
    if not gaze_ndjsons:
        print(f"ERROR: no gaze NDJSON files found — run bids_tobii_tsv_to_ndjson.py first", file=sys.stderr)
        sys.exit(1)

    # Load shared world geometry from template
    with template_path.open(encoding="utf-8") as fh:
        tmpl = yaml.safe_load(fh)

    # Keep world geometry, desk, table_marker_layout, fixed_charuco_board from template
    out: dict = {}
    for key in ("world", "desk", "table_marker_layout", "fixed_charuco_board"):
        if key in tmpl:
            out[key] = tmpl[key]

    # Build devices block — only participants that have BOTH scene video AND gaze NDJSON
    devices = []
    participants = sorted(set(scene_videos) | set(gaze_ndjsons))
    for pid in participants:
        sv = scene_videos.get(pid)
        ndjson = gaze_ndjsons.get(pid)
        if ndjson is None:
            print(f"  Skipping {pid}: no gaze NDJSON", file=sys.stderr)
            continue
        entry: dict = {
            "id": f"tobii_{pid}",
            "gaze_ndjson": str(ndjson).replace("\\", "/"),
            "video_fps_override": None,
            "video_time_offset_s": 0.0,
            "intrinsics": {
                "width": 1920, "height": 1080,
                "fx": _TOBII_FX_DEFAULT, "fy": _TOBII_FX_DEFAULT,
                "cx": 960.0, "cy": 540.0,
                "dist_coeffs": [0.0, 0.0, 0.0, 0.0, 0.0],
            },
        }
        if sv:
            entry["scene_video"] = str(sv).replace("\\", "/")
        else:
            entry["scene_video"] = None
            print(f"  {pid}: no scene video — gaze-only (world coords won't be computed)", file=sys.stderr)
        devices.append(entry)

    out["devices"] = devices

    # Write with a header comment
    header = (
        f"# World-gaze alignment config for {ses_name}, task {task}\n"
        f"# Auto-generated by tools/generate_world_align_config.py\n"
        f"# Participants: {', '.join(f'{p} (video={p in scene_videos})' for p in participants)}\n"
        f"#\n"
        f"# Run command:\n"
        f"#   python tools/tobii_multi_glasses_world_align.py \\\n"
        f"#       --config {output_path.name} \\\n"
        f"#       --output-dir <session_dir>/gaze_world_{task} \\\n"
        f"#       --ticks-per-second 1 \\\n"
        f"#       --ray-source gaze2d\n"
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as fh:
        fh.write(header + "\n")
        yaml.dump(out, fh, default_flow_style=False, allow_unicode=True, sort_keys=False)

    print(f"Wrote: {output_path}")
    print(f"  Devices: {len(devices)} ({sum(1 for d in devices if d.get('scene_video'))} with scene video)")


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Generate session world-align YAML config")
    p.add_argument("--session-dir", required=True, type=Path)
    p.add_argument("--task", default="T1")
    p.add_argument("--template", type=Path,
                   default=Path("configs/tobii_offline_world_align.example.yaml"))
    p.add_argument("--output", type=Path)
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    out = args.output or (
        Path("configs") / f"tobii_offline_world_align_{args.session_dir.name}_{args.task}.yaml"
    )
    generate(args.session_dir, args.task, args.template, out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
